### PR TITLE
Fix counter label and add snapshot tests

### PR DESCRIPTION
**Pull request by victorBaro**
This PR fixes autolayout issues in the counter label.

It also adds snapshot tests to the project so hopefully this kind of bugs won't happen again in future releases.

### CODE REVIEW

**Comment by seecahkhing** [comment]
Hi @victorBaro : This would help a lot...Would it be OK to merge this one and have it released?

**Comment by victorBaro** [comment]
@seecahkhing I am waiting for a code review from one of my teammates. Will merge as soon as I have a 👍 

In the meantime, you can refer your pod to this specific branch with something like:
`pod 'AnimatedTextInput', :branch => 'fix-counter-label'`

**Comment by seecahkhing** [comment]
Got it.. I was able to do 
`pod 'AnimatedTextInput', :git => 'https://github.com/jobandtalent/AnimatedTextInput.git', :branch => 'fix-counter-label'`

One more thing though, the size of the font is always constant during typing and it's not using the Custom AnimatedTextInputStyle. This happens for .multiline style only...

http://imgur.com/a/9TD14

**Comment by victorBaro** [comment]
Well spotted @seecahkhing 
Thank you!

I have just fixed it [here](https://github.com/jobandtalent/AnimatedTextInput/pull/53/commits/2322fd56ef0b48f1b05eddfdf924fd6d7712d236)

**Review by luisrecuenco — APPROVED** [review]

**Pull request merged**
